#!/usr/bin/env ruby
#^syntax detection
site 'https://supermarket.getchef.com/api/v1'

cookbook 'apt', '~> 2.8.2'
cookbook 'build-essential', '~> 2.2.3'
cookbook 'nodejs', '~> 2.4.2'
cookbook 'postgresql', '~> 3.4.20'
